services:
  docker-harbor:
    build: .
    container_name: docker-harbor
    restart: unless-stopped
    ports:
      - "6969:6969"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./descriptions.json:/app/descriptions.json
      - /home/fredrik/Projects:/home/fredrik/Projects
    env_file:
      - .env
    labels:
      description: "Huvudsaklig kontrollpanel för Docker-containers på servern (Live
        redigerad)."
